'$include:'bin\part\-00 - 0 - Load.txt'
    '$include:'bin\part\000 - 0 - Introduction.txt'
    '$include:'bin\part\001 - Z - Start MapleStory.txt'
    '$include:'bin\part\002 - A - Character.txt'
    '$include:'bin\part\003 - S - Calculator.txt'
    '$include:'bin\part\004 - C - Experience.txt'
    '$include:'bin\part\005 - D - Guild.txt'
    '$include:'bin\part\006 - Q - Monsters.txt'
    '$include:'bin\part\007 - W - Items.txt'
    '$include:'bin\part\008 - E - Quests.txt'
    '$include:'bin\part\009 - R - Maps.txt'
    '$include:'bin\part\010 - T - Classes.txt'
    '$include:'bin\part\011 - Y - Skills.txt'
    '$include:'bin\part\012 - U - NPCs.txt'
    '$include:'bin\part\013 - I - Pets.txt'
    '$include:'bin\part\014 - O - Gachapon.txt'
    '$include:'bin\part\015 - P - Fashion.txt'
    '$include:'bin\part\016 - F - Reactor.txt'
    '$include:'bin\part\017 - J - Cash Shop.txt'
    '$include:'bin\part\018 - G - Guides.txt'
    '$include:'bin\part\019 - H - Party Quests.txt'
    '$include:'bin\part\020 - B - Facts & Tips.txt'
    '$include:'bin\part\021 - N - Jukebox.txt'
    '$include:'bin\part\022 - M - Gallery.txt'
    '$include:'bin\part\023 - K - Options.txt'
    '$include:'bin\part\024 - L - Credits.txt'
'$include:'bin\part\998 - 9 - Outroduction.txt'
'$include:'bin\part\999 - 9 - Appendix.txt'