'database array dimensioning
REDIM SHARED index_item(1 TO 0) AS _UNSIGNED LONG
REDIM SHARED index_map(1 TO 0) AS _UNSIGNED LONG
REDIM SHARED index_monster(1 TO 0) AS _UNSIGNED LONG
REDIM SHARED index_npc(1 TO 0) AS _UNSIGNED LONG
REDIM SHARED index_quest(1 TO 0) AS _UNSIGNED LONG
REDIM SHARED index_spell(1 TO 0) AS _UNSIGNED LONG